name: Deploying Hugo site to GH Pages

on:
  push:
    branches: [main] 
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 1 
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version

    - name: Setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.79.1'
    
    - name: Update theme  
      run: git submodule update --init --recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: install node
      run: 
       npm ci
       mv node_modules ../..
        
   # - name: installing node
   #   run: 
   #     npm install --only=dev
   #     mv node_modules ../..   
    
    - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/          
      run: git submodule add --force git@github.com:bep/docuapi.git themes/docuapi
    - run: hugo
 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: true
        # keep_files: true
        #   cname: example.com
