name: Deploying Hugo site to GH Pages

on:
  push:
    branches: [main]
        
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules: recursive
          fetch-depth: 1 
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
      
      - name: Update theme  
        run:   git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
      
      - name: cache files
        uses: actions/cache@v2
        with:
          path: ${TMPDIR}/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-  
    
      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/          
        run:
          git submodule add git@github.com:bep/docuapi.git themes/docuapi
          hugo --minify
 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        #  publish_dir: ./public
        # keep_files: true
        #   cname: example.com
